#!/bin/sh
#
# David Valdivieso <dvaldivieso@koghi.com>
# JULIO 2020
#

set -e
ENV_FILE=".env"
rm -f $ENV_FILE
touch $ENV_FILE

echo DEBUG=TRUE >> $ENV_FILE

echo MONGODB_NAME=surCompany >> $ENV_FILE
echo MONGODB_HOST=localhost >> $ENV_FILE
echo MONGODB_PORT=27017 >> $ENV_FILE
echo MONGODB_USER=SUR >> $ENV_FILE
echo MONGODB_PASSWORD=SUR123 >> $ENV_FILE
echo MONGODB_POOL_SIZE=1 >> $ENV_FILE
echo MONGODB_REPLICA_SET_NAME=rs >> $ENV_FILE

# HOSTS
echo MS_CORE_HOOK_HOST=ms_core_hook >> $ENV_FILE
echo MS_CORE_CRON_HOST=ms_core_cron >> $ENV_FILE
echo MS_ESB_INVENTORIES_HOST=ms_esb_inventories >> $ENV_FILE
echo MS_ESB_ORDER_HOST=ms_esb_order >> $ENV_FILE
echo MS_ESB_PRICES_HOST=ms_esb_prices >> $ENV_FILE
echo MS_ESB_PRODUCT_HOST=ms_esb_product >> $ENV_FILE
echo MS_ESB_QUEUE_HOST=ms_esb_queue >> $ENV_FILE
echo MS_SAP_API_HOST=ms_sap_api >> $ENV_FILE
echo MS_VTEX_API_HOST=ms_vtex_api >> $ENV_FILE

# PORTS
echo MS_CORE_HOOK_PORT=20001 >> $ENV_FILE
echo MS_CORE_CRON_PORT=16001 >> $ENV_FILE
echo MS_ESB_INVENTORIES_PORT=19001 >> $ENV_FILE
echo MS_ESB_ORDER_PORT=18001 >> $ENV_FILE
echo MS_ESB_PRICES_PORT=17001 >> $ENV_FILE
echo MS_ESB_PRODUCT_PORT=13001 >> $ENV_FILE
echo MS_ESB_QUEUE_PORT=13002 >> $ENV_FILE
echo MS_SAP_API_PORT=15002 >> $ENV_FILE
echo MS_VTEX_API_PORT=15001 >> $ENV_FILE

# ENVERIOMENTS OF PRODUCT API
echo FORCE_ESPECIFICATIONS_MAPPING_REPOPULATION=FALSE >> $ENV_FILE

# ENVERIOMENTS OF VTEX API
echo VTEX_REST_API_BASE_PATH=https://tuvertical.vtexcommercestable.com.br/api/ >> $ENV_FILE
echo VTEX_REST_API_APP_KEY=vtexappkey-tuvertical-GAIZCD >> $ENV_FILE
echo VTEX_REST_API_APP_TOKEN=JRJWJOGVQMPFGCKPCCFTWWUTBHYLVYFKZFYSKHSLMAJCWGAIWOFDKPQMWQVBPUARGFGAESEVJUHVNRWUHQPGTCZKPMVULQWRARWRAZEDKKTQHUZETBTZETYEFVLSXKKT >> $ENV_FILE
echo VTEX_REST_API_ACCOUNT_NAME=tuvertical >> $ENV_FILE
echo VTEX_REST_API_HOST=https://api.vtex.com/ >> $ENV_FILE
echo VTEX_REST_API_TRACKER_BASE_PATH=https://conversationtracker.vtex.com.br/api/ >> $ENV_FILE
echo VTEX_REST_API_TRACKER=pvt/emailMapping >> $ENV_FILE
echo VTEX_REST_API_PRODUCT=catalog/pvt/product >> $ENV_FILE
echo VTEX_REST_API_SKU=catalog/pvt/stockkeepingunit >> $ENV_FILE
echo VTEX_REST_API_PRICES=pricing/prices >> $ENV_FILE
echo VTEX_REST_API_HOOK=orders/hook/config >> $ENV_FILE
echo VTEX_REST_API_ORDERS=oms/pvt/orders >> $ENV_FILE
echo VTEX_REST_API_INVENTORY=logistics/pvt/inventory/skus >> $ENV_FILE
echo VTEX_REST_API_WAREHOUSE_ID=1_1 >> $ENV_FILE

# ENVERIOMENTS OF SAP API
echo IGNORE_SSL=TRUE >> $ENV_FILE
echo SAP_SERVICE_LAYER_BASE_PATH=https://200.85.225.126:50000/b1s/v1 >> $ENV_FILE
echo SAP_SERVICE_LAYER_COMPANY_DB=20210630_VTEX_SURCOMPANY >> $ENV_FILE
echo SAP_SERVICE_LAYER_USER_NAME=manager >> $ENV_FILE
echo SAP_SERVICE_LAYER_PASSWORD=HYC909 >> $ENV_FILE
echo SAP_WAREHOUSES="AMERICAN,SUR" >> $ENV_FILE
echo SAP_ADVANCE_INVOICE_DOWNPAYMENTTYPE=dptInvoice >> $ENV_FILE
echo SAP_ADVANCE_INVOICE_ITEMCODE="ANTICIPO CLIENTE" >> $ENV_FILE
echo SAP_ADVANCE_INVOICE_QUANTITY=1 >> $ENV_FILE
echo SAP_ADVANCE_INVOICE_VATGROUP=IVAG3 >> $ENV_FILE
echo SAP_ADVANCE_INVOICE_TAXLIABLE=tNO >> $ENV_FILE
echo SAP_ADVANCE_INVOICE_WTLIABLE=tNO >> $ENV_FILE
echo SAP_PAYMENT_RECEIVED_DOCCURRENCY=$ >> $ENV_FILE
echo SAP_PAYMENT_RECEIVED_INVOICETYPE=it_DownPayment >> $ENV_FILE
echo SAP_PAYMENT_RECEIVED_DOCTYPE=rCustomer >> $ENV_FILE
echo SAP_PAYMENT_RECEIVED_LINENUM=0 >> $ENV_FILE

# ENVERIOMENTS OF ORDERS API
echo SAP_CLIENT_ADDRESS_NAME=PRINCIPAL >> $ENV_FILE
echo SAP_CLIENT_DOCUMENT_TYPE=13 >> $ENV_FILE
echo SAP_U_SOL_ORIGEN=2 >> $ENV_FILE
echo SAP_CLIENT_GROUP_CODE=103 >> $ENV_FILE
echo SAP_CLIENT_PRICE_LIST=8 >> $ENV_FILE
echo SAP_SERIE_KEY_WORD=Vtex >> $ENV_FILE
echo SAP_ORDER_SERIE=17 >> $ENV_FILE
echo SAP_INVOICE_SERIE=203 >> $ENV_FILE
echo SAP_PAYMENT_SERIE=24 >> $ENV_FILE

# ENVERIOMENTS OF HOOK API
echo PAYMENT_APPROVED_HOOK_NAME=payment_approved_hook >> $ENV_FILE

# ENVERIOMENTS OF CRON API
echo MILLISECONDS_REPEAT=86400000 >> $ENV_FILE
echo CRON_CREATE_SKU_PRICES_PATTERNS="00 08 * * *,00 13 * * *,11 10 * * *" >> $ENV_FILE
echo MILLISECONDS_SKU_PRICES_FAILED_REPEAT=270000 >> $ENV_FILE
echo MILLISECONDS_PRODUCT_FAILED_REPEAT=250000 >> $ENV_FILE
echo MILLISECONDS_INVENTORIES_FAILED_REPEAT=210000 >> $ENV_FILE
echo MILLISECONDS_PRODUCT_REPEAT=180000 >> $ENV_FILE
echo MILLISECONDS_CHECK_INVOICE_REPEAT=150000 >> $ENV_FILE
echo MILLISECONDS_CHECK_INVOICE_FAILED_REPEAT=160000 >> $ENV_FILE
echo MILLISECONDS_GET_ORDER_V2S_FAILED_REPEAT=240000 >> $ENV_FILE
echo MILLISECONDS_INVENTORIES_REPEAT=240000 >> $ENV_FILE

cat $ENV_FILE
